name = "91-worker"              #  Worker 名称（不能有空格）
main = "main.js"                 # 入口文件是 main.js
compatibility_date = "2025-08-06" # 今天日期

# 如果有 KV、Durable Objects、环境变量，可以在下面加
# [vars]
# MY_KEY = "123456"
